### ISSUE TITLE
allowing the archive to be created at s3 root level

### ISSUE THREAD

**Issue by fasatrix** [francismeynard/lambda-s3-archiver#7]
Hi there (@dennismonsewicz  @guillaume-tgl @francismeynard ),

I cloned the repo and wanted raise a PR with some changes and tried to push in a branch, but I was given permission denied.

Basically I'd like the possibility to have the archive created at S3 root level.

The change should be `line 31` of `index.js`

From: 
      ` const outputFilePath = '${sourcePath}/${outputFilename}.${format}' ;`
To :
     `  const outputFilePath = sourcePath ? '${sourcePath}/${outputFilename}.${format}' : '${outputFilename}.${format}';`

Would you mind add me as contributor or alternatively add this feature? 

Much appreciated
F.

**Comment by francismeynard** [comment]
Hey - thanks for your interest to contribute into this repo.

There are already two guys already contributed to this repo and they just simply sent PRs and I just approved them - but I think that was before I enabled 2-FA on my account.

Btw, do you have 2-FA enabled? If it is ok with you, could you try enable 2-FA for your account (this will also add security for your account), and please try to raise a PR again? Let me know otherwise, and I'll find time to make you changes.

Thanks!

**Comment by fasatrix** [comment]
Yes I do have the 2-FA but cannot raise a PR

**Comment by fasatrix** [comment]
@francismeynard  here it is thanks. https://github.com/francismeynard/lambda-s3-archiver/pull/8

**Comment by francismeynard** [comment]
All good, I have merged your PR. Thanks @fasatrix  for contributing! :)

**Comment by fasatrix** [comment]
> All good, I have merged your PR. Thanks @fasatrix for contributing! :)

Hi @francismeynard  thanks for that, and happy to help. When do you think the new npm version will be ready with this changes? Cheers

**Comment by francismeynard** [comment]
It's now available in npm repo - https://www.npmjs.com/package/lambda-s3-archiver version 1.4.0

**Comment by fasatrix** [comment]
@francismeynard thanks alot
